laravel/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/account/{id}', 'HomeController@accountSettings')->name('account');
Route::put('/account/{id}', 'HomeController@saveAccountSettings')->name('account.update');


Route::resource('page', 'PageController');

Route::get('user/export', 'UserController@export')->name('user.export');
Route::resource('user', 'UserController');

Route::resource('task', 'TaskController');
Route::post('task/{id}/{time}', 'TaskController@saveTime')->name('task.save-time');

Route::get('hour/export', 'HourController@export')->name('hour.export');

Route::resource('hour', 'HourController');
Route::resource('status', 'StatusController');

laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});
Auth::routes();

laravel/app/Http/Controllers/cms/HomeController.php
<?php namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Status;
use App\Task;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{

    public function index()
    {
        $view = view('cms.index');
        $view->title = 'Dashboard';
        $view->total_users = User::with('tasks', 'tasks.status')->get();
        $view->total_users_count = $view->total_users->count();
        $view->total_tasks_count = Task::all()->count();
        $view->statuses = Status::with('tasks')->get();
        $total_hours_count = [];
        foreach ($view->total_users as $user) {
            foreach ($user->tasks as $task) {
                $task = Auth::user()->tasks->find($task->id);
                if(isset($task->pivot)) {
                    $total_hours_count[] = $task->pivot->seconds;
                }
            }
        }
        $view->total_hours_count = collect($total_hours_count)->sum();

        return $view;
    }
    public function accountSettings($id)
    {
        $view = view('cms.account');
        $view->title = 'Mijn Account';
        $view->user = User::find($id);
        return $view;
    }
    public function saveAccountSettings(Request $request, $id)
    {
       $user = User::find($id);
       $user->update($request->all());
       return redirect()->back()->withMessage('Veranderingen opgeslagen');

    }
}

laravel/app/Http/Controllers/cms/HourController.php
<?php namespace App\Http\Controllers\Admin;


use App\Exports\TimeRegistrationExport;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class HourController extends Controller
{
    public function index()
    {
        $view = view('cms.hour.index');
        $view->title = 'Uren';
        $view->users = User::with(['tasks', 'tasks.status'])->get();
        return $view;
    }
    public function export()
    {
        return Excel::download(new TimeRegistrationExport, 'time_registarion_'.date('m_d_y').'.xlsx');
    }
}

laravel/app/Http/Controllers/cms/PageController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreatePageRequest;
use App\Page;
use Illuminate\Http\Request;

class PageController extends Controller
{

    public function index()
    {
        $view = view('cms.page.index');
        $view->pages = Page::all();
        $view->title = "Pagina's";

        return $view;
    }


    public function create()
    {
        $view = view('cms.page.create');
        $view->title = 'Pagina toevoegen';
        return $view;
    }


    public function store(CreatePageRequest $request)
    {
       $page = Page::create([
           'title' => $request->title,
           'url' => Page::titleToUrl($request->title)
       ]);
       return redirect()->route('admin.page.edit', $page->id)->withMessage('Pagina aangemaakt en gepubliceert');
    }

    public function show(Page $page)
    {
        dd($page);
    }

    public function edit(Page $page)
    {
        $view = view('cms.page.edit');
        $view->title = $page->title;
        $view->page = $page;

        return $view;
    }

    public function update(Request $request, Page $page)
    {
        //
    }


    public function destroy(Page $page)
    {
        //
    }
}

laravel/app/Http/Controllers/cms/StatusController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StatusRequest;
use App\Status;

class StatusController extends Controller
{
    public function index()
    {
        $view = view('cms.status.index');
        $view->title = 'Statussen';
        $view->statuses = Status::all();
        return $view;
    }

    public function create()
    {
        $view = view('cms.status.create');
        $view->title = 'Nieuwe Status';

        return $view;
    }

    public function store(StatusRequest $request)
    {
        $status = Status::create($request->all());
        return redirect()->route('admin.status.edit', $status->id)->withMessage('Nieuwe status: '. $status->name. ' aangemaakt');

    }

    public function edit(Status $status)
    {
        $view = view('cms.status.edit');
        $view->title = 'Status bewerken';
        $view->status = $status;

        return $view;
    }

    public function update(StatusRequest $request, Status $status)
    {
        $status->update($request->all());
        return redirect()->route('admin.status.edit', $status->id)->withMessage('Status is bijgewerkt');
    }

    public function destroy(Status $status)
    {
        dd('todo');
    }
}

laravel/app/Http/Controllers/cms/TaskController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TaskRequest;
use App\Status;
use App\Task;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{

    public function index()
    {
        $view = view('cms.task.index');
        $view->title = 'Taken';
        $view->tasks = Task::orderBy('created_at', 'DESC')->with('status', 'users')->paginate(12);
        return $view;
    }

    public function create()
    {
        $view = view('cms.task.create');
        $view->title = 'Taak Toevoegen';
        $view->statuses = Status::pluck('name', 'id');
        return $view;
    }

    public function store(TaskRequest $request)
    {
        $task = Task::create($request->all());
        $task->users()->attach(Auth::id(),['seconds' => 0]);
        return redirect()->route('admin.task.edit', $task->id)->withMessage('Taak aangemaakt');
    }

    public function edit(Task $task)
    {
        $view = view('cms.task.edit');
        $view->task = $task;
        $view->title = 'Taak bewerken';
        $view->statuses = Status::pluck('name', 'id');
        $worked_users = [];
        foreach ($task->users as $user){
            if($user->pivot->seconds > 0){
                $user->pivot->updated_at = Task::convertCreatedAt($user->pivot->updated_at);
                $worked_users[] = $user;
            }
        }
        $view->users = $worked_users;
        if(Auth::user()->tasks->find($task->id) != null){
            $view->seconds = Auth::user()->tasks->find($task->id)->pivot->seconds;
        }else{
            $view->seconds = 0;
        }
        return $view;
    }

    public function update(TaskRequest $request, Task $task)
    {
        $task->update($request->all());
        return redirect()->route('admin.task.edit', $task->id)->withMessage('Taak is bijgewerkt');
    }


    public function destroy(Task $task)
    {
        $task->users()->wherePivot('task_id','=',$task->id)->detach();
        $task->delete();
        return redirect()->route('admin.task.index')->withMessage('Taak verwijderd');
    }
    public function saveTime($id, $time)
    {
        $task = Task::find($id);
        $seconds = strtotime("1970-01-01 $time UTC");
        Auth::user()->tasks()->detach($task->id, ['seconds' => $seconds]);
        Auth::user()->tasks()->attach($task->id, ['seconds' => $seconds]);
        return response('OK');
    }
}

laravel/app/Http/Controllers/cms/UserController.php
<?php namespace App\Http\Controllers\Admin;

use App\Exports\UserExport;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Facades\Excel;

class UserController extends Controller
{
    public function index()
    {
        $view = view('cms.user.index');
        $view->title = 'Administrators';
        $view->users = User::paginate(10);
        return $view;
    }

    public function create()
    {
        $view = view('cms.user.create');
        $view->title = 'Administrator toevoegen';
        return $view;
    }

    public function store(UserRequest $request)
    {
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        User::create($input);
        return redirect()->route('admin.user.index')->withMessage('Administrator aangemaakt');
    }


    public function edit(User $user)
    {
       $view = view('cms.user.edit');
       $view->user = $user;
       $view->title = 'Administrator bewerken';
       return $view;
    }

    public function update(UserRequest $request, User $user)
    {
        $input = $request->except('user_id');
        $input['password'] = Hash::make($input['password']);
        $user->update($input);
        return redirect()->route('admin.user.edit', $user->id)->withMessage('Administrator is bijgewerkt');
    }

    public function destroy(User $user)
    {
        $name = $user->name;
        $user->tasks()->wherePivot('user_id','=',$user->id)->detach();
        $user->delete();
        return redirect()->route('admin.user.index')->withMessage('Administrator '.$name.' is verwijderd');
    }
    public function export()
    {
        return Excel::download(new UserExport, 'users_'.date('m_d_y').'.xlsx');
    }
}

laravel/resources/views/cms/task/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4">
                <div class="card-header">
                    {{ $title }}
                </div>
                <div class="card-body">
                    {{ Form::open(['route' =>'admin.task.store']) }}
                    @include('cms.task.form')
                    <button type="submit" class="btn btn-sm btn-custom pull-right mt-4">Toevoegen</button>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Uren Registratie Huidige Taak
                </div>
                <div class="card-body text-center">
                    Maak eerst de taak aan voordat de urenregistratie gestart kan worden
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/cms/task/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    {{ $title }}
                </div>
                <div class="card-body">
                    {{ Form::model($task,['route' =>['admin.task.update', $task->id], 'method' => 'PUT']) }}
                    @include('cms.task.form')
                    <button type="submit" class="btn btn-sm btn-custom pull-right mt-4">Bewerken</button>
                    <button type="button" class="btn btn-sm btn-danger pull-right mt-4" data-toggle="modal"
                            data-target="#deleteModal">Taak verwijderen
                    </button>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card h-100">
                <div class="card-header">
                    Uren Registratie Huidige Taak
                </div>
                <div class="card-body text-center">
                    <div style="font-size: 5.3rem;padding-top: 100px;" class="timer"></div>
                    <button type="button" class="btn btn-lg btn-primary w-50 start-time"
                            onclick="$('.timer').countimer('resume');">Start
                    </button>
                    <button type="button" style="display: none" class="btn btn-lg btn-warning w-50 stop-time"
                            onclick="$('.timer').countimer('stop');">Stop
                    </button>
                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card h-100 mt-xl-5 mb-xl-5">
                <div class="card-header">
                    Gebruikers die gewerkt hebben aan deze taak
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th><b>Naam</b></th>
                            <th><b>Gewerkte Tijd</b></th>
                            <th><b>Voor het laatst aan gewerkt</b></th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($users as $user)
                            <tr>
                                <td width="10%">{{ $user->name }}@if(Auth::id() == $user->id) <span class="text-danger">(Mijzelf)</span> @endif</td>
                                <td width="10%">{{ gmdate("H:i:s", $user->pivot->seconds) }}</td>
                                <td width="10%">{{ $user->pivot->updated_at->format('d-m-Y H:i') }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3">Niemand heeft nog gewerkt aan deze taak</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

    {{ Form::close() }}
    {{ Form::open(['route' => ['admin.task.destroy' ,$task->id], 'method' => 'DELETE', 'id' => 'delete']) }}
    {{ Form::close() }}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Weet u zeker dat u taak {{ $task->number }} wil
                        verwijderen?</h5>
                </div>
                <div class="modal-body">
                    <p><span class="text-danger">Waarschuwing!</span><br>Als u deze taak verwijderd, worden ook alle geregistreerde uren van deze taak verwijderd!</p>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-sm btn-success" onclick="$('#delete').submit()">Ja</a>
                    <a class="btn btn-sm btn-danger" data-dismiss="modal">Nee</a>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('script')
    <script>
        $('.timer').countimer({
            autoStart: false,
            initSeconds: {{ $seconds }}
        });
        $('.start-time').click(function () {
            $(this).hide();
            $('.stop-time').show();
        });
        $('.stop-time').click(function () {
            $(this).hide();
            $('.start-time').show();
            var time = $('.timer').text();
            var url = "{{ route('admin.task.save-time', ['id' => $task->id,'time'=> 'time']) }}";
            var _token = $("input[name='_token']").val();
            var task = "{{ $task->id }}";
            url = url.replace('time', time);
            $.ajax({
                type: "POST",
                url: url,
                data: {_token: _token, task: task, time: time},
                beforeSend: function () {
                    $('.stop-time').attr('disabled', true);
                },
                success: function (data) {
                    toastr.success('', 'Tijd opgeslagen', {timeOut: 3000, progressBar: true});
                    setTimeout(function () {
                        $('.stop-time').attr('disabled', false);
                    }, 2000);
                }
            });
        });
    </script>
@endsection

laravel/resources/views/cms/task/form.blade.php
<div class="md-form">
    {{ Form::text('name', old('name'), ['class' => 'form-control', 'id'=> 'nameBox']) }}
    <label for="nameBox">Naam</label>
</div>

<span style="color: #757575">Status</span>
{{ Form::select('status_id', $statuses,null,['class'=>'mdb-select md-form mt-0','placeholder' => 'Selecteer een status']) }}

<span style="color: #757575;">Omschrijving</span>
<textarea placeholder="test" name="description" id="editor">
        @if(isset($task)) {!! $task->description !!} @else {!! old('description') !!} @endif
</textarea>

laravel/resources/views/cms/task/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="card mb-5">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <span class="head-title">{{ $title }}</span>
                </div>
                <div class="col-md-6">
                    <a href="{{ route('admin.task.create') }}" class="btn btn-sm btn-custom pull-right">Nieuwe Taak</a>
                    <a href="#" class="btn btn-sm btn-custom pull-right"><i class="fas fa-search"></i></a>
                    <div class="md-form form-sm d-inline-block m-0 pull-right">
                        <input name="search" type="text" id="inputSMEx" class="form-control form-control-sm">
                        <label for="inputSMEx">Taak zoeken</label>
                    </div>
                    {{ Form::open(['route' => 'admin.task.index']) }}
                </div>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover table-responsive">
                <thead>
                <tr class="text-center">
                    <th><b>Naam</b></th>
                    <th><b>Omschrijving</b></th>
                    <th><b>Mijn Gewerkte Tijd</b></th>
                    <th><b>Status</b></th>
                    <th><b>Opties</b></th>
                </tr>
                </thead>
                <tbody>
                @forelse($tasks as $task)
                    <tr class="text-center  ">
                        <td width="20%">{{ $task->name }}</td>
                        <td width="45%"><a href="#" class="show-description text-primary"
                                           id="{{$task->id}}">Weergeven</a>
                            <div id="taskDescription_{{$task->id}}" style="display: none;">
                                <hr>
                                {!! $task->description !!}
                                <hr>
                            </div>
                        </td>
                        <td width="20%" style="padding-top: 22px;">
                            @if($task->users->where('id', Auth::id())->first())
                                <span>
                                    {{ gmdate('H:i:s', $task->users->where('id', Auth::id())->first()->pivot->seconds) }}
                                </span>
                            @endif
                        </td>
                        <td width="25%">
                            <span class="badge w-100 h-100"
                                  style="background-color: {{ $task->status->color }};padding: .7rem 1.6rem;">{{ $task->status->name }}</span>
                        </td>
                        <td>
                            <a class="btn btn-sm btn-info w-100" href="{{ route('admin.task.edit', $task->id) }}">
                                <i class="fas fa-edit"></i>
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr data-url="{{ route('admin.task.create')}}">
                        <td colspan="2">Nog geen taken aangemaakt.</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            {{ $tasks->render() }}
        </div>
    </div>
@endsection
@section('script')
    <script>
        $('.show-description').click(function () {
            var id = $(this).attr('id');
            if ($(this).text() === 'Weergeven') {
                $(this).text('Verbergen');
            } else {
                $(this).text('Weergeven');
            }
            $('#taskDescription_' + id).toggle();
        });
    </script>
@endsection