laravel/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/account/{id}', 'HomeController@accountSettings')->name('account');
Route::put('/account/{id}', 'HomeController@saveAccountSettings')->name('account.update');


Route::resource('page', 'PageController');

Route::get('user/export', 'UserController@export')->name('user.export');
Route::resource('user', 'UserController');

Route::resource('task', 'TaskController');
Route::post('task/{id}/{time}', 'TaskController@saveTime')->name('task.save-time');

Route::get('hour/export', 'HourController@export')->name('hour.export');

Route::resource('hour', 'HourController');
Route::resource('status', 'StatusController');

laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});
Auth::routes();

laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ public_path('favicon-16x16.png') }}">
    <title>{{ $title }}</title>
    {!! HTML::style('css/mdb.min.css') !!}
    {!! HTML::style('css/app.css') !!}
    {!! HTML::style('css/bootstrap.min.css') !!}
    <script src="//cdn.ckeditor.com/4.11.3/standard/ckeditor.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    @yield('style')
</head>
<body id="app">
@include('layouts.side_nav')
@include('layouts.upper_nav')
<main class="content-wrapper">
    @if(!$errors->isEmpty())
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            @foreach($errors->all() as $error)
                {{ $error }}<br>
            @endforeach
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @yield('content')
</main>
{!! HTML::script('js/app.js') !!}

{!! HTML::script('js/jquery-3.3.1.min.js') !!}
{!! HTML::script('js/popper.min.js') !!}
{!! HTML::script('js/mdb.min.js') !!}
{!! HTML::script('js/moment.js') !!}
{!! HTML::script('js/ez.countimer.min.js') !!}
{!! HTML::script('js/colorpicker.js') !!}
<script>
    CKEDITOR.replace( 'editor' );
    CKEDITOR.config.toolbar = [
        ['Styles','Format','Font','FontSize','Bold','Italic','Underline','StrikeThrough','-','Undo','Redo','-','Cut','Copy','Paste','Find','Replace','-','Outdent','Indent','-','Print'],
        ['NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
        [,'Table','-','Link','Flash','Smiley','TextColor','BGColor','Source']
    ] ;
</script>
<script>
    $(".button-collapse").sideNav();
    $('.mdb-select').materialSelect();
    $('.clickable tr').click(function () {
        window.location.href = $(this).data('url');
    });
</script>
@if(Session::has('message'))
    <script>
        toastr.success('', '{{ Session::get('message') }}', {timeOut: 3000, progressBar: true});
    </script>
@endif
@yield('script')
</body>
</html>

laravel/resources/views/layouts/side_nav.blade.php
<div id="slide-out" class="side-nav fixed site-color">
    <ul>
        <li>
            <div class="logo-wrapper">
                <img src="{{ asset('images/logo.png') }}" class="img-fluid flex-center">
            </div>
        </li>
        <li>
            <ul class="collapsible collapsible-accordion">
                <li class="@if(Request::is('admin')) custom-active @endif">
                    <a href="{{ route('admin.home') }}" class="collapsible-header waves-effect">
                        <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                </li>
                <li class="@if(Request::is('admin/task*')) custom-active @endif">
                    <a href="{{ route('admin.task.index') }}" class="collapsible-header waves-effect">
                        <i class="fas fa-tasks"></i>Taken</a>
                </li>
                <li class="@if(Request::is('admin/user*')) custom-active @endif">
                    <a href="{{ route('admin.user.index') }}" class="collapsible-header waves-effect">
                        <i class="fas fa-users"></i>Administrators</a>
                </li>
                <li class="@if(Request::is('admin/hour*')) custom-active @endif">
                    <a href="{{ route('admin.hour.index') }}" class="collapsible-header waves-effect">
                        <i class="fas fa-clock "></i>Uren</a>
                </li>
                <li class="@if(Request::is('admin/status*')) custom-active @endif">
                    <a href="{{ route('admin.status.index') }}" class="collapsible-header waves-effect">
                        <i class="fas fa-list"></i>Statussen</a>
                </li>
                {{--<li><a class="collapsible-header waves-effect arrow-r"><i class="fas fa-cog"></i> Instellingen<i class="fas fa-angle-down rotate-icon"></i></a>--}}
                    {{--<div class="collapsible-body">--}}
                        {{--<ul class="list-unstyled">--}}
                            {{--<li><a href="#" class="waves-effect">1</a>--}}
                            {{--</li>--}}
                            {{--<li><a href="#" class="waves-effect">2</a>--}}
                            {{--</li>--}}
                        {{--</ul>--}}
                    {{--</div>--}}
                {{--</li>--}}
            </ul>
        </li>
        <!--/. Side navigation links -->
    </ul>
    <div class="sidenav-bg mask-strong"></div>
</div>

laravel/resources/views/layouts/upper_nav.blade.php
<nav class="navbar fixed-top navbar-toggleable-md navbar-expand-lg site-color text-white">
    <!-- SideNav slide-out button -->
    <div class="float-left">
        <a href="#" style="color: white!important;" data-activates="slide-out" class="button-collapse black-text"><i class="fas fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav nav-flex-icons ml-auto">
        {{--<li class="nav-item">--}}
        {{--<a class="nav-link waves-effect waves-light"><i class="fas fa-user"></i> <span class="clearfix d-none d-sm-inline-block">{{ Auth::user()->name }}</span></a>--}}
        {{--</li>--}}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false"><i class="fas fa-user"></i> {{ Auth::user()->name }}</a>
            <div class="dropdown-menu site-color" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item site-color-text waves-effect waves-light" href="{{route('admin.account', Auth::id()) }}">Account</a>
                <a class="dropdown-item site-color-text waves-effect" href="#"
                   onclick="$('#logout').submit()">Logout</a>
                {{ Form::open(['route' => 'logout', 'id' => 'logout']) }}
                {{Form::close()}}
            </div>
        </li>
    </ul>

</nav>