laravel/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/account/{id}', 'HomeController@accountSettings')->name('account');
Route::put('/account/{id}', 'HomeController@saveAccountSettings')->name('account.update');


Route::resource('page', 'PageController');

Route::get('user/export', 'UserController@export')->name('user.export');
Route::resource('user', 'UserController');

Route::resource('task', 'TaskController');
Route::post('task/{id}/{time}', 'TaskController@saveTime')->name('task.save-time');

Route::get('hour/export', 'HourController@export')->name('hour.export');

Route::resource('hour', 'HourController');
Route::resource('status', 'StatusController');

laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});
Auth::routes();

laravel/app/Http/Controllers/cms/HomeController.php
<?php namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Status;
use App\Task;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{

    public function index()
    {
        $view = view('cms.index');
        $view->title = 'Dashboard';
        $view->total_users = User::with('tasks', 'tasks.status')->get();
        $view->total_users_count = $view->total_users->count();
        $view->total_tasks_count = Task::all()->count();
        $view->statuses = Status::with('tasks')->get();
        $total_hours_count = [];
        foreach ($view->total_users as $user) {
            foreach ($user->tasks as $task) {
                $task = Auth::user()->tasks->find($task->id);
                if(isset($task->pivot)) {
                    $total_hours_count[] = $task->pivot->seconds;
                }
            }
        }
        $view->total_hours_count = collect($total_hours_count)->sum();

        return $view;
    }
    public function accountSettings($id)
    {
        $view = view('cms.account');
        $view->title = 'Mijn Account';
        $view->user = User::find($id);
        return $view;
    }
    public function saveAccountSettings(Request $request, $id)
    {
       $user = User::find($id);
       $user->update($request->all());
       return redirect()->back()->withMessage('Veranderingen opgeslagen');

    }
}

laravel/app/Http/Controllers/cms/HourController.php
<?php namespace App\Http\Controllers\Admin;


use App\Exports\TimeRegistrationExport;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class HourController extends Controller
{
    public function index()
    {
        $view = view('cms.hour.index');
        $view->title = 'Uren';
        $view->users = User::with(['tasks', 'tasks.status'])->get();
        return $view;
    }
    public function export()
    {
        return Excel::download(new TimeRegistrationExport, 'time_registarion_'.date('m_d_y').'.xlsx');
    }
}

laravel/app/Http/Controllers/cms/PageController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreatePageRequest;
use App\Page;
use Illuminate\Http\Request;

class PageController extends Controller
{

    public function index()
    {
        $view = view('cms.page.index');
        $view->pages = Page::all();
        $view->title = "Pagina's";

        return $view;
    }


    public function create()
    {
        $view = view('cms.page.create');
        $view->title = 'Pagina toevoegen';
        return $view;
    }


    public function store(CreatePageRequest $request)
    {
       $page = Page::create([
           'title' => $request->title,
           'url' => Page::titleToUrl($request->title)
       ]);
       return redirect()->route('admin.page.edit', $page->id)->withMessage('Pagina aangemaakt en gepubliceert');
    }

    public function show(Page $page)
    {
        dd($page);
    }

    public function edit(Page $page)
    {
        $view = view('cms.page.edit');
        $view->title = $page->title;
        $view->page = $page;

        return $view;
    }

    public function update(Request $request, Page $page)
    {
        //
    }


    public function destroy(Page $page)
    {
        //
    }
}

laravel/app/Http/Controllers/cms/StatusController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StatusRequest;
use App\Status;

class StatusController extends Controller
{
    public function index()
    {
        $view = view('cms.status.index');
        $view->title = 'Statussen';
        $view->statuses = Status::all();
        return $view;
    }

    public function create()
    {
        $view = view('cms.status.create');
        $view->title = 'Nieuwe Status';

        return $view;
    }

    public function store(StatusRequest $request)
    {
        $status = Status::create($request->all());
        return redirect()->route('admin.status.edit', $status->id)->withMessage('Nieuwe status: '. $status->name. ' aangemaakt');

    }

    public function edit(Status $status)
    {
        $view = view('cms.status.edit');
        $view->title = 'Status bewerken';
        $view->status = $status;

        return $view;
    }

    public function update(StatusRequest $request, Status $status)
    {
        $status->update($request->all());
        return redirect()->route('admin.status.edit', $status->id)->withMessage('Status is bijgewerkt');
    }

    public function destroy(Status $status)
    {
        dd('todo');
    }
}

laravel/app/Http/Controllers/cms/TaskController.php
<?php namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TaskRequest;
use App\Status;
use App\Task;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{

    public function index()
    {
        $view = view('cms.task.index');
        $view->title = 'Taken';
        $view->tasks = Task::orderBy('created_at', 'DESC')->with('status', 'users')->paginate(12);
        return $view;
    }

    public function create()
    {
        $view = view('cms.task.create');
        $view->title = 'Taak Toevoegen';
        $view->statuses = Status::pluck('name', 'id');
        return $view;
    }

    public function store(TaskRequest $request)
    {
        $task = Task::create($request->all());
        $task->users()->attach(Auth::id(),['seconds' => 0]);
        return redirect()->route('admin.task.edit', $task->id)->withMessage('Taak aangemaakt');
    }

    public function edit(Task $task)
    {
        $view = view('cms.task.edit');
        $view->task = $task;
        $view->title = 'Taak bewerken';
        $view->statuses = Status::pluck('name', 'id');
        $worked_users = [];
        foreach ($task->users as $user){
            if($user->pivot->seconds > 0){
                $user->pivot->updated_at = Task::convertCreatedAt($user->pivot->updated_at);
                $worked_users[] = $user;
            }
        }
        $view->users = $worked_users;
        if(Auth::user()->tasks->find($task->id) != null){
            $view->seconds = Auth::user()->tasks->find($task->id)->pivot->seconds;
        }else{
            $view->seconds = 0;
        }
        return $view;
    }

    public function update(TaskRequest $request, Task $task)
    {
        $task->update($request->all());
        return redirect()->route('admin.task.edit', $task->id)->withMessage('Taak is bijgewerkt');
    }


    public function destroy(Task $task)
    {
        $task->users()->wherePivot('task_id','=',$task->id)->detach();
        $task->delete();
        return redirect()->route('admin.task.index')->withMessage('Taak verwijderd');
    }
    public function saveTime($id, $time)
    {
        $task = Task::find($id);
        $seconds = strtotime("1970-01-01 $time UTC");
        Auth::user()->tasks()->detach($task->id, ['seconds' => $seconds]);
        Auth::user()->tasks()->attach($task->id, ['seconds' => $seconds]);
        return response('OK');
    }
}

laravel/app/Http/Controllers/cms/UserController.php
<?php namespace App\Http\Controllers\Admin;

use App\Exports\UserExport;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Support\Facades\Hash;
use Maatwebsite\Excel\Facades\Excel;

class UserController extends Controller
{
    public function index()
    {
        $view = view('cms.user.index');
        $view->title = 'Administrators';
        $view->users = User::paginate(10);
        return $view;
    }

    public function create()
    {
        $view = view('cms.user.create');
        $view->title = 'Administrator toevoegen';
        return $view;
    }

    public function store(UserRequest $request)
    {
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        User::create($input);
        return redirect()->route('admin.user.index')->withMessage('Administrator aangemaakt');
    }


    public function edit(User $user)
    {
       $view = view('cms.user.edit');
       $view->user = $user;
       $view->title = 'Administrator bewerken';
       return $view;
    }

    public function update(UserRequest $request, User $user)
    {
        $input = $request->except('user_id');
        $input['password'] = Hash::make($input['password']);
        $user->update($input);
        return redirect()->route('admin.user.edit', $user->id)->withMessage('Administrator is bijgewerkt');
    }

    public function destroy(User $user)
    {
        $name = $user->name;
        $user->tasks()->wherePivot('user_id','=',$user->id)->detach();
        $user->delete();
        return redirect()->route('admin.user.index')->withMessage('Administrator '.$name.' is verwijderd');
    }
    public function export()
    {
        return Excel::download(new UserExport, 'users_'.date('m_d_y').'.xlsx');
    }
}

laravel/resources/views/cms/user/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            {{ $title }}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    {{ Form::open(['route' =>'admin.user.store']) }}
                    @include('cms.user.form')
                </div>
            </div>
            <button type="submit" class="btn btn-sm btn-custom pull-right">Toevoegen</button>
            {{ Form::close() }}

        </div>
    </div>
@endsection

laravel/resources/views/cms/user/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="card-title"><span class="head-title">{{ $title }}</span></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ Form::model($user,['route' =>['admin.user.update', $user->id], 'method' => 'PUT']) }}
                    {{ Form::hidden('user_id', $user->id) }}
                    @include('cms.user.form')
                </div>
            </div>
            <button type="submit" class="btn btn-sm btn-custom pull-right">Bewerken</button>
            <button type="button" class="btn btn-sm btn-danger pull-right" data-toggle="modal" data-target="#deleteModal">Administrator verwijderen</button>
            {{ Form::close() }}
            {{ Form::open(['route' => ['admin.user.destroy' ,$user->id], 'method' => 'DELETE', 'id' => 'delete']) }}
            {{ Form::close() }}
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Weet u zeker dat u {{ $user->name }} wil verwijderen?</h5>
                        </div>
                        <div class="modal-body">
                            <p><span class="text-danger">Waarschuwing!</span><br>Als u deze user verwijderd, worden ook alle uren van deze user verwijderd!</p>
                        </div>
                        <div class="modal-footer">
                            <a class="btn btn-sm btn-danger" data-dismiss="modal">Nee</a>
                            <a class="btn btn-sm btn-success" onclick="$('#delete').submit()">Ja</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravel/resources/views/cms/user/form.blade.php
<div class="md-form">
    {{ Form::text('name', old('name'), ['class' => 'form-control', 'id'=> 'nameBox']) }}
    <label for="nameBox">Naam</label>
</div>
<div class="md-form md-outline">
    {{ Form::email('email',  old('email'), ['class' => 'form-control', 'id'=> 'emailBox']) }}
    <label for="emailBox">Email</label>
</div>
<div class="md-form">
    <input type="password" name="password" id="passwordBox" class="form-control">
    <label for="passwordBox">Wachtwoord</label>
</div>
<div class="md-form">
    <input type="password" name="password_confirmation" id="password_conBox" class="form-control" >
    <label for="password_conBox">Wachtwoord bevestigen</label>
</div>

laravel/resources/views/cms/user/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="card mb-5">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <span class="head-title">{{ $title }}</span>
                </div>
                <div class="col-md-6">
                    <a href="{{ route('admin.user.create') }}" class="btn btn-sm btn-custom pull-right">Nieuwe Administrator</a>
                    <a href="{{ route('admin.user.export') }}" class="btn btn-sm btn-primary pull-right">Download user overzicht</a>
                </div>
            </div>
        </div>
        <div class="card-body">

            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th><b>Naam</b></th>
                    <th><b>Email</b></th>
                </tr>
                </thead>
                <tbody class="clickable">
                @foreach($users as $user)
                    <tr data-url="@if(Auth::id() == $user->id) {{ route('admin.account', $user->id)}}  @else {{ route('admin.user.edit', $user->id)}} @endif">
                        <td width="40%">{{ $user->name }} @if(Auth::id() == $user->id) <span class="text-danger">(Mijzelf)</span> @endif</td>
                        <td width="40%">{{ $user->email }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $users->render() }}
        </div>
    </div>
@endsection